/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.epn.prograii.pkg2022a.aplicacionbancaria;

/**
 *
 * @author Alex
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPantalla1 = new javax.swing.JPanel();
        fondoPantalla2 = new javax.swing.JPanel();
        labelCuentaCorriente = new javax.swing.JLabel();
        txtNumCuenta1 = new javax.swing.JTextField();
        txtSaldo1 = new javax.swing.JTextField();
        labelIcon = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelCuentaAhorro = new javax.swing.JLabel();
        txtNumCuenta2 = new javax.swing.JTextField();
        txtSaldo2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labelCredito = new javax.swing.JLabel();
        txtSaldoCredito = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPantalla1.setBackground(new java.awt.Color(255, 255, 153));
        fondoPantalla1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPantalla2.setBackground(new java.awt.Color(255, 153, 153));
        fondoPantalla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoPantalla2MouseClicked(evt);
            }
        });

        labelCuentaCorriente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labelCuentaCorriente.setText("Cuenta Corriente");

        txtNumCuenta1.setText("28880085689");
        txtNumCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCuenta1ActionPerformed(evt);
            }
        });

        txtSaldo1.setText("$330.56");
        txtSaldo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoPantalla2Layout = new javax.swing.GroupLayout(fondoPantalla2);
        fondoPantalla2.setLayout(fondoPantalla2Layout);
        fondoPantalla2Layout.setHorizontalGroup(
            fondoPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPantalla2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCuentaCorriente)
                    .addGroup(fondoPantalla2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNumCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(txtSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        fondoPantalla2Layout.setVerticalGroup(
            fondoPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPantalla2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCuentaCorriente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        fondoPantalla1.add(fondoPantalla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 430, -1));

        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Diseño_sin_título-removebg-preview.png"))); // NOI18N
        fondoPantalla1.add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtNombreUsuario.setBackground(new java.awt.Color(204, 255, 204));
        txtNombreUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtNombreUsuario.setText("JUAN CARLOS");
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        fondoPantalla1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        labelCuentaAhorro.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        labelCuentaAhorro.setText("Cuenta Ahorro");

        txtNumCuenta2.setText("33886828584");

        txtSaldo2.setText("$ 3550.98");
        txtSaldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelCuentaAhorro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtNumCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(txtSaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCuentaAhorro)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        fondoPantalla1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 430, -1));

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));

        labelCredito.setFont(new java.awt.Font("Segoe UI Emoji", 2, 14)); // NOI18N
        labelCredito.setText("Crédito");

        txtSaldoCredito.setText("$3000");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelCredito)
                .addGap(148, 148, 148)
                .addComponent(txtSaldoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelCredito))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtSaldoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        fondoPantalla1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 430, 80));

        getContentPane().add(fondoPantalla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtNumCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumCuenta1ActionPerformed

    private void txtSaldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldo1ActionPerformed

    private void fondoPantalla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoPantalla2MouseClicked
        Login v1=new Login();
        v1.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_fondoPantalla2MouseClicked

    private void txtSaldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoPantalla1;
    private javax.swing.JPanel fondoPantalla2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCredito;
    private javax.swing.JLabel labelCuentaAhorro;
    private javax.swing.JLabel labelCuentaCorriente;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNumCuenta1;
    private javax.swing.JTextField txtNumCuenta2;
    private javax.swing.JTextField txtSaldo1;
    private javax.swing.JTextField txtSaldo2;
    private javax.swing.JTextField txtSaldoCredito;
    // End of variables declaration//GEN-END:variables
}
