/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.epn.prograii.pkg2022a.aplicacionbancaria;

import static ec.edu.epn.prograii.pkg2022a.aplicacionbancaria.Login.usua1;
import javax.swing.Timer;

/**
 *
 * @author PC
 */
public class VentanaExitosaAgua extends javax.swing.JFrame {
    /*Variables que reciben los datos de la cuenta*/
    float Pago;
    String Sumi;
    String Descri;
    String usuario;
    float monto;
    int cuenta;
    float saldo;
   
    public VentanaExitosaAgua() {
        initComponents();
        this.setLocation(500, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblserv = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblasunto = new javax.swing.JLabel();
        lblpagoo = new javax.swing.JLabel();
        lblagua = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        Descr = new javax.swing.JLabel();
        IrSB = new javax.swing.JButton();
        TituPago = new javax.swing.JLabel();
        lblhaspagado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblserv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblserv.setText("Servicio:");
        jPanel2.add(lblserv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNum.setText("Número de Suministro:");
        jPanel2.add(lblNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblasunto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblasunto.setText("Asunto:");
        jPanel2.add(lblasunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        lblpagoo.setText("0");
        jPanel2.add(lblpagoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 127, -1));

        lblagua.setText("Agua Potable");
        jPanel2.add(lblagua, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 127, -1));

        lblnumero.setText("0");
        jPanel2.add(lblnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 127, -1));

        Descr.setText("Comentario");
        jPanel2.add(Descr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 127, -1));

        IrSB.setText("Pagar otro servicio");
        IrSB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IrSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrSBActionPerformed(evt);
            }
        });
        jPanel2.add(IrSB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, 35));

        TituPago.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        TituPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituPago.setText("Pago exitoso");
        jPanel2.add(TituPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        lblhaspagado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblhaspagado.setText("Has pagado: ");
        jPanel2.add(lblhaspagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 254));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*Metodos que reciben los datos necesarios para la transaccion*/
    public void setValorpago(float Pago){
        this.Pago = Pago;
        lblpagoo.setText(String.valueOf(Pago));
    }

    public void setSuministro(String Sumi){
        this.Sumi= Sumi;
        lblnumero.setText(Sumi);
    }

    public void setDescripcion(String Descri){
        this.Descri = Descri;
        Descr.setText(Descri);
    }
    
    /*Actualiza los valores base de la cuenta y volvemos a la ventana servicios basicos*/
    private void IrSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrSBActionPerformed
        //actualizarSaldoCuenta();
        VentanaServiciosBasicos regresar = new VentanaServiciosBasicos();
        regresar.mostrarCuentaCompleta(usuario, cuenta, saldo);
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IrSBActionPerformed
    
    /*Recibe los valores de la cuenta usuario*/
    public void mostrarCuentaCompleta(String usuario, int cuenta, float saldo){
        this.usuario=usuario;
        this.cuenta=cuenta;
        this.saldo=saldo;
    }
    
    /*Metodo que actualiza los valores base de la cuenta que estemos utilizando
    public void actualizarSaldoCuenta(){
        if (Home.tipoCuenta==0) {
                this.saldo=(saldo-(Pago));
                usua1.setValoragua(0);
                usua1.setSaldoCorriente(this.saldo);
        }else if(Home.tipoCuenta==1){
                this.saldo=(saldo-(Pago));
                usua1.setValoragua(0);
                usua1.setSaldoAhorro(this.saldo);
        }else if(Home.tipoCuenta==2){
                this.saldo=(saldo-(Pago));
                usua1.setValoragua(0);
                usua1.setSaldoCredito(this.saldo);
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descr;
    private javax.swing.JButton IrSB;
    private javax.swing.JLabel TituPago;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblagua;
    private javax.swing.JLabel lblasunto;
    private javax.swing.JLabel lblhaspagado;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblpagoo;
    private javax.swing.JLabel lblserv;
    // End of variables declaration//GEN-END:variables
}
