/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.epn.prograii.pkg2022a.aplicacionbancaria;

import static ec.edu.epn.prograii.pkg2022a.aplicacionbancaria.Login.usua1;
import javax.swing.Timer;

/**
 *
 * @author PC
 */
public class VentanaExitosaAgua extends javax.swing.JFrame {
    float Pago;
    String Sumi;
    String Descri;
    String usuario;
    float monto;
    int cuenta;
    float saldo;
    public Timer tiempo;
   
  
    /**
     * Creates new form VentanaExitosaAgua
     */
    public VentanaExitosaAgua() {
        initComponents();
        this.setLocation(500, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituPago = new javax.swing.JLabel();
        lblhaspagado = new javax.swing.JLabel();
        lblserv = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblasunto = new javax.swing.JLabel();
        lblpagoo = new javax.swing.JLabel();
        lblagua = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        Descr = new javax.swing.JLabel();
        IrSB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituPago.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        TituPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituPago.setText("Pago exitoso");

        lblhaspagado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblhaspagado.setText("Has pagado: ");

        lblserv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblserv.setText("Servicio:");

        lblNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNum.setText("Número de Suministro:");

        lblasunto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblasunto.setText("Asunto:");

        lblpagoo.setText("0");

        lblagua.setText("Agua Potable");

        lblnumero.setText("0");

        Descr.setText("Comentario");

        IrSB.setText("Pagar otro servicio");
        IrSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrSBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(TituPago)
                            .addGap(89, 89, 89))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNum)
                                .addComponent(lblasunto)
                                .addComponent(lblhaspagado)
                                .addComponent(lblserv))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblnumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblagua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblpagoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Descr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(IrSB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituPago)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhaspagado)
                    .addComponent(lblpagoo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblserv)
                    .addComponent(lblagua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum)
                    .addComponent(lblnumero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblasunto)
                    .addComponent(Descr))
                .addGap(18, 18, 18)
                .addComponent(IrSB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void setValorpago(float Pago){
    this.Pago = Pago;
    lblpagoo.setText(String.valueOf(Pago));
}

public void setSuministro(String Sumi){
    this.Sumi= Sumi;
    lblnumero.setText(Sumi);
}

public void setDescripcion(String Descri){
    this.Descri = Descri;
    Descr.setText(Descri);
}
    private void IrSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrSBActionPerformed
        actualizarSaldoCuenta();
        VentanaServiciosBasicos regresar = new VentanaServiciosBasicos();
        regresar.mostrarCuentaCompleta(usuario, cuenta, saldo);
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IrSBActionPerformed
    public void mostrarCuentaCompleta(String usuario, int cuenta, float saldo){
        this.usuario=usuario;
        this.cuenta=cuenta;
        this.saldo=saldo;
    }
    public void actualizarSaldoCuenta(){
        if (Home.tipoCuenta==0) {
                this.saldo=(saldo-(Pago));
                usua1.setValoragua(0);
                usua1.setSaldoCorriente(this.saldo);
        }else if(Home.tipoCuenta==1){
                this.saldo=(saldo-(Pago));
                usua1.setValoragua(0);
                usua1.setSaldoCorriente(this.saldo);
        }else if(Home.tipoCuenta==2){
                this.saldo=(saldo-(Pago));
                usua1.setValoragua(0);
                usua1.setSaldoCorriente(this.saldo);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descr;
    private javax.swing.JButton IrSB;
    private javax.swing.JLabel TituPago;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblagua;
    private javax.swing.JLabel lblasunto;
    private javax.swing.JLabel lblhaspagado;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lblpagoo;
    private javax.swing.JLabel lblserv;
    // End of variables declaration//GEN-END:variables
}
